<a href="https://colab.research.google.com/github/caplove/DX_team_4_repo/blob/main/Team_4_Batch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **데이터 가져오기**

---

In [ ]:
!git clone https://github.com/caplove/DX_team_4_repo.git

fatal: destination path 'DX_team_4_repo' already exists and is not an empty directory.

In [ ]:
#과제 설명
from IPython.display import Image
#Image('./image/image_01.png',width=800,height=600)

## 데이터 프레임

In [ ]:
"""함수 불러오기 """
from augment_import2 import augment2
from extractor_import import extractor
from models_import import my_models

"""데이터 import"""
from data_import import *
print(x.shape,y.shape)

""" """
features_all = pd.DataFrame()
# jittering / MagWarp / Scaling / Combination
x_in_jittering = pd.DataFrame()
x_in_MagWarp = pd.DataFrame()
x_in_Scaling = pd.DataFrame()
x_in_Combination = pd.DataFrame()

"""전역변수"""
global x,y,x_list

./DX_team_4_repo/Data//idle.txt
./DX_team_4_repo/Data//coat_1.txt
./DX_team_4_repo/Data//suit_5.txt
./DX_team_4_repo/Data//shirt_4.txt
./DX_team_4_repo/Data//suit_3.txt
./DX_team_4_repo/Data//coat_2.txt
./DX_team_4_repo/Data//coat_3.txt
./DX_team_4_repo/Data//shirt_1.txt
./DX_team_4_repo/Data//coat_5.txt
./DX_team_4_repo/Data//suit_2.txt
./DX_team_4_repo/Data//shirt_5.txt
./DX_team_4_repo/Data//coat_4.txt
./DX_team_4_repo/Data//shirt_2.txt
./DX_team_4_repo/Data//shirt_3.txt
./DX_team_4_repo/Data//suit_1.txt
./DX_team_4_repo/Data//suit_4.txt

In [ ]:
import pandas as pd

"""변수"""
jitter_para_list = [0.01, 0.05, 0.1]  # sigma
MW_para_list =     [0.01, 0.05, 0.1]  # sigma
Scale_para_list =  [0.01, 0.05, 0.1]

log_en = 0   # 0 : 결과만 보임,  1 : 중간 과정 보임.

df = pd.DataFrame(columns=['jit','MW','Scale','DNN','MLP','DTree','KNN','AdaBoost','RandomForest'])

for i in jitter_para_list:
    for j in MW_para_list:
        for k in Scale_para_list:
            
            print(f"jitter_sigma:{i},   MW_sigma:{j},   Scale_sigma:{k}")
            # augmentation 방법별로 원본 x와 동일 size의 데이터 생성
            x_in_jittering, x_in_MagWarp, x_in_Scaling, x_in_Combination = augment2(x,y,i,j,k,log_en)
            #print(x.shape, x_in_jittering.shape, x_in_MagWarp.shape, x_in_Scaling.shape, x_in_Combination.shape, y.shape)
            print("status: 데이터 증강 완료")

            # 증강 데이터 선정
            # dataset_list = [x]                                                               # default 데이터
            dataset_list = [x,x_in_jittering, x_in_MagWarp,x_in_Scaling, x_in_Combination]   # 증강    데이터
            
            # 원본 포함 증강된 데이터의 특징 추출하고 merge            
            features_all = extractor(x,y,dataset_list,log_en)
            print("status: Features 추출 완료")

            # 특징 데이터 기반 모든 모델에 대한 훈련 및 평가
            Acc_DNN,Acc_MLP,Acc_TREE,Acc_KNN,Acc_Ensemble, Acc_RForest = my_models(features_all,log_en)
            print("status: 모형 훈련/평가 완료")

            print(f"DNN: {Acc_DNN:.3f}, MLP:{Acc_MLP:.3f}, DTree:{Acc_TREE:.3f}, KNN:{Acc_KNN:.3f}, AdaBoost: {Acc_Ensemble:.3f}, RandomForest: {Acc_RForest:.3f}")
            print("----" * 30)

            # parameter별 Accuracy 데이터 저장
            df=df.append({'jit':i,'MW':j,'Scale':k,'DNN':Acc_DNN,'MLP':Acc_MLP,'DTree':Acc_TREE,'KNN':Acc_KNN,'AdaBoost':Acc_Ensemble,'RandomForest':Acc_RForest},ignore_index=True)

print(df) 


# default
# DNN: 0.940, MLP:0.902, DTree:0.759, KNN:0.940, AdaBoost: 0.714, RandomForest: 0.872

   accx  accy  accz  gyrx  gyry  gyrz  current CLASS
0   0.0   0.0   1.0  0.18  1.04 -1.46    -0.02  idle
1   0.0  -0.0   1.0  0.24  0.98 -1.46    -0.02  idle
2   0.0  -0.0   1.0  0.06  1.04 -1.28    -0.06  idle
3   0.0  -0.0   1.0 -0.06  0.98 -1.40    -0.09  idle
4   0.0  -0.0   1.0  0.06  1.10 -1.34     0.01  idle

In [ ]:
"""시각화"""
import matplotlib.pyplot as plt
import matplotlib
plt.style.use('seaborn-whitegrid')
import seaborn as sns
#sns.set_style("white")
import itertools
# %matplotlib inline
import pandas as pd

""" 실험데이터 불러오기"""

df = pd.read_csv("./accuracy.csv",index_col=0)

#df['avg_accuracy']=df.iloc[:,3:-1].mean(axis=1)   
idx1=df.jit==0.01
idx2=df.jit==0.05
idx3=df.jit==0.1
plt.figure(figsize=(10,5))
plt.title('models\' average accuracy')

plt.plot(df.avg_accuracy[idx1],label='augment(jitter_sigma=0.01,MW,Scale)')
plt.plot(df.avg_accuracy[idx2],label='augment(jitter_sigma=0.05,MW,Scale)')
plt.plot(df.avg_accuracy[idx3],label='augment(jitter_sigma=0.1, MW,Scale)')
plt.axhline(y=0.854, color='r',linestyle = 'dashed',label='no augment')
plt.ylim([0.5, 1])
plt.legend(loc='lower left')

# no augment 성능
# DNN: 0.940, MLP:0.902, DTree:0.759, KNN:0.940, AdaBoost: 0.714, RandomForest: 0.872

       accx  accy  accz  gyrx  gyry  gyrz  current   CLASS
14689 -0.01  0.07  1.05 -1.28  1.28 -1.28    -0.57  suit_4
14690 -0.00  0.02  0.86  2.44  0.98 -1.46    -0.64  suit_4
14691 -0.00 -0.04  1.11  0.12  1.04 -1.22    -0.06  suit_4
14692  0.01  0.02  0.91 -0.55  1.16 -1.40     0.94  suit_4
14693  0.01 -0.05  1.06 -0.61  1.28 -1.40    -0.06  suit_4

In [ ]:
""" 실험데이터 저장"""
# df.to_csv("accuracy.csv", mode='a', header=True)

,accx,accy,accz,gyrx,gyry,gyrz,current
count,274582.000000,274582.000000,274582.000000,274582.000000,274582.000000,274582.000000,274582.000000
mean,-0.000210,-0.000524,0.998872,0.263806,1.062795,-1.314019,0.084912
std,0.018129,0.035233,0.059794,1.455410,0.179769,0.192238,0.619515
min,-0.180000,-0.190000,0.570000,-15.630000,0.060000,-2.140000,-3.630000
25%,-0.010000,-0.020000,0.970000,-0.550000,0.980000,-1.400000,-0.480000
50%,0.000000,-0.000000,1.000000,0.240000,1.040000,-1.280000,0.070000
75%,0.010000,0.020000,1.030000,1.040000,1.160000,-1.220000,0.650000
max,0.140000,0.220000,1.440000,15.560000,2.320000,-0.430000,1.810000

## x,y 정의